<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN" xml:lang="zh-CN">
<head>
	<?= $this->headMeta()?>
	<?= $this->headTitle()?>
	<?= $this->headStyle()?>
	<?= $this->headLink()?>
	<?= $this->headScript()?>
</head>
	<h1 class="noDisplay">
		<?= $this->placeholder('Zend_View_Helper_HeadTitle');?>
	</h1>
	<div id="headwrap" class="clearfix">
		<div class="right">
			<?= $this->render('_topnav.phtml')?>
		</div>
		<div id="logo" class="left">
			<img alt="教师圈..." src="/images/layout/logo.png">
		</div>
	</div>
	<div id="contentWrap" class="clearfix">
		<div class="left categorylist">
			项目分类
		</div>
		<div class="content left">
			<?= $this->layout()->content ?>
		</div>
	</div>
	<div id="footer" class="clearfix">
		<div class="left">
			<span class="rss">
				<a href="/rss" title="products feed">RSS 2.0</a>
			</span>
		</div>
		<div class="right">&#169; 2009 刘铭</div>
	</div>
</html>